config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#dashboard"

  # My Companies
  resources :companies, only: [:new, :create, :show, :index]

  # My expanses & Reciepts
  resources :expenses do
    resource :receipt, only: [:show, :create, :destroy]
  end

  resources :receipts, only: [:new, :create, :show, :edit, :update, :destroy]

  # My Clients & Projects
  resources :clients, only: [:new, :create, :show, :index]
  resources :projects, only: [:new, :create, :show, :index]

  # My invoices
  resources :invoices, only: [:new, :create, :show, :index] do
    resources :invoice_items, only: [:create, :update, :destroy], shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :company

  # has_many :projects
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  has_many :clients
  # has_many :expenses
  # has_many :invoices
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :company
  belongs_to :client
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :companies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :dashboard ]

  def dashboard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashMoneyBitches</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="container my-5 header-secondary">
    <h3><%= Date.today.strftime("%B %d, %Y").upcase %></h3>
    <h3><%= Date.today.strftime("%A").upcase %></h3>
    <p class="mt-4">Add your invoices, hours or clients here</p>
  </div>

  <div class="container mb-5 d-flex justify-content-between align-items-center">
    <div class="btn-dashboard-purple">
      <%= link_to 'INVOICE', new_invoice_path, class: 'm-1' %>
    </div>

    <div class="btn-dashboard-purple">
      <%= link_to 'TIME', new_expense_path, class: 'm-1' %>
    </div>

    <div class="btn-dashboard-purple">
      <%= link_to 'RECEIPT', new_expense_path, class: 'm-1' %>
    </div>

    <div class="btn-dashboard-purple">
      <%= link_to 'CLIENTS', clients_path, class: 'm-1' %>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-main">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'emmvs.png' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link nav-link-main" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/emmvs", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link nav-link-main" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>